#!/usr/bin/env bash
set -euo pipefail

# =============================================================================
# ailegal.sh — Mike Platform Orchestrator
# Dynamic port allocation, self-locating paths, health-gated boot, watchdog.
# =============================================================================

# ---------------------------------------------------------------------------
# P-1: Self-locating paths (no hardcoded paths, ever)
# ---------------------------------------------------------------------------
SELF="$(readlink -f "${BASH_SOURCE[0]}" 2>/dev/null || realpath "${BASH_SOURCE[0]}")"
ROOT="$(cd "$(dirname "$SELF")" && pwd)"
cd "$ROOT"

COMPOSE="docker compose"
PROJECT_NAME="mike"
BACKUP_DIR="${ROOT}/backups"
PORTS_FILE="${ROOT}/.ports"
ENV_FILE="${ROOT}/.env"
WATCHDOG_MAX_RETRIES="${WATCHDOG_MAX_RETRIES:-3}"

# ---------------------------------------------------------------------------
# Colors
# ---------------------------------------------------------------------------
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
BOLD='\033[1m'
DIM='\033[2m'
NC='\033[0m'

# ---------------------------------------------------------------------------
# P-0: Canonical port table (single source of truth)
# Every port-binding service MUST appear here. docker-compose.yml reads these
# as ${VAR:-default}. No port literals anywhere else.
# ---------------------------------------------------------------------------
PORT_LABELS=(  postgres  redis  minio_api  minio_console  gotrue  postgrest  pgadmin  glitchtip  backend  frontend  nginx)
PORT_VARS=(    POSTGRES_PORT REDIS_PORT MINIO_API_PORT MINIO_CONSOLE_PORT GOTRUE_PORT POSTGREST_PORT PGADMIN_PORT GLITCHTIP_PORT BACKEND_PORT FRONTEND_PORT NGINX_PORT)
PORT_DEFAULTS=(5432      6379   9000       9001           9999    3002       5050     8000       3001     3000       80)
PORT_SERVICES=(postgres  redis  minio      minio          gotrue  postgrest  pgadmin  glitchtip  backend  frontend  nginx)

BOOT_ORDER=(postgres redis minio gotrue postgrest pgadmin glitchtip glitchtip-worker backend frontend nginx)

# Health probe endpoints (HTTP or command)
declare -A HEALTH_PROBES=(
  [postgres]="cmd:pg_isready -U \${POSTGRES_USER:-mike}"
  [redis]="cmd:redis-cli ping"
  [minio]="http://localhost:\${MINIO_API_PORT:-9000}/minio/health/live"
  [gotrue]="http://localhost:\${GOTRUE_PORT:-9999}/health"
  [postgrest]="http://localhost:\${POSTGREST_PORT:-3002}/"
  [pgadmin]="http://localhost:\${PGADMIN_PORT:-5050}/misc/ping"
  [glitchtip]="http://localhost:\${GLITCHTIP_PORT:-8000}/_health/"
  [backend]="http://localhost:\${BACKEND_PORT:-3001}/health"
  [frontend]="http://localhost:\${FRONTEND_PORT:-3000}/"
  [nginx]="http://localhost:\${NGINX_PORT:-80}/health"
)

# ---------------------------------------------------------------------------
# Logging
# ---------------------------------------------------------------------------
log_info()  { echo -e "${BLUE}[INFO]${NC}  $*"; }
log_ok()    { echo -e "${GREEN}[ OK ]${NC} $*"; }
log_warn()  { echo -e "${YELLOW}[WARN]${NC}  $*"; }
log_error() { echo -e "${RED}[ERR ]${NC} $*"; }
log_step()  { echo -e "${BOLD}${CYAN}▸${NC} $*"; }

# ---------------------------------------------------------------------------
# Port management (P-0 enforcement)
# ---------------------------------------------------------------------------

is_port_free() {
  local port="$1"
  if command -v ss &>/dev/null; then
    ! ss -tlnH "sport = :$port" 2>/dev/null | grep -q .
  elif command -v netstat &>/dev/null; then
    ! netstat -tlnp 2>/dev/null | grep -q ":$port "
  else
    ! (echo >/dev/tcp/127.0.0.1/"$port") 2>/dev/null
  fi
}

load_ports() {
  for i in "${!PORT_VARS[@]}"; do
    local var="${PORT_VARS[$i]}"
    local default="${PORT_DEFAULTS[$i]}"
    if [ -z "${!var:-}" ]; then
      export "${var}=${default}"
    fi
  done
  if [ -f "$PORTS_FILE" ]; then
    log_info "Loading port overrides from .ports"
    # shellcheck disable=SC1090
    source "$PORTS_FILE"
    for v in "${PORT_VARS[@]}"; do export "$v"; done
  fi
}

save_ports() {
  {
    echo "# Mike port allocation — generated by ailegal.sh"
    echo "# $(date -Iseconds)"
    for i in "${!PORT_VARS[@]}"; do
      echo "${PORT_VARS[$i]}=${!PORT_VARS[$i]}"
    done
  } > "$PORTS_FILE"
}

find_free_port() {
  local start="$1"
  local port="$start"
  local max=$((start + 100))
  while [ "$port" -lt "$max" ]; do
    if is_port_free "$port"; then
      echo "$port"
      return 0
    fi
    port=$((port + 1))
  done
  echo "$start"
  return 1
}

ensure_dynamic_ports() {
  load_ports
  local conflicts=0
  for i in "${!PORT_VARS[@]}"; do
    local var="${PORT_VARS[$i]}"
    local port="${!var}"
    local label="${PORT_LABELS[$i]}"
    local service="${PORT_SERVICES[$i]}"
    if ! is_port_free "$port"; then
      local container_name="${PROJECT_NAME}-${service}-1"
      local holder
      holder=$(docker inspect --format='{{.Name}}' "$container_name" 2>/dev/null || echo "")
      if [ -n "$holder" ]; then
        continue
      fi
      log_warn "Port $port ($label) is in use — finding alternative..."
      local new_port
      new_port=$(find_free_port "$((port + 10))")
      export "${var}=${new_port}"
      log_info "  $label: $port → $new_port"
      conflicts=$((conflicts + 1))
    fi
  done
  if [ "$conflicts" -gt 0 ]; then
    save_ports
    log_info "Port overrides saved to .ports ($conflicts conflicts resolved)"
  fi
  for v in "${PORT_VARS[@]}"; do export "$v"; done
}

cmd_ports() {
  load_ports
  echo ""
  echo -e "${BOLD}Mike Platform — Port Allocation${NC}"
  echo ""
  printf "${CYAN}%-18s %-8s %-12s %-10s${NC}\n" "SERVICE" "PORT" "ENV VAR" "STATUS"
  printf "%-18s %-8s %-12s %-10s\n" "─────────────────" "──────" "───────────" "─────────"
  for i in "${!PORT_LABELS[@]}"; do
    local label="${PORT_LABELS[$i]}"
    local var="${PORT_VARS[$i]}"
    local port="${!var}"
    local service="${PORT_SERVICES[$i]}"
    local status_color="$GREEN"
    local status_text="free"
    if ! is_port_free "$port"; then
      local container_name="${PROJECT_NAME}-${service}-1"
      local holder
      holder=$(docker inspect --format='{{.Name}}' "$container_name" 2>/dev/null || echo "")
      if [ -n "$holder" ]; then
        status_text="ours"
        status_color="$GREEN"
      else
        status_text="CONFLICT"
        status_color="$RED"
      fi
    fi
    printf "%-18s %-8s %-12s ${status_color}%-10s${NC}\n" "$label" "$port" "$var" "$status_text"
  done
  echo ""
}

cmd_ports_auto() {
  log_step "Auto-allocating ports to resolve conflicts..."
  for i in "${!PORT_VARS[@]}"; do
    local var="${PORT_VARS[$i]}"
    export "${var}=${PORT_DEFAULTS[$i]}"
  done
  ensure_dynamic_ports
  cmd_ports
}

# ---------------------------------------------------------------------------
# Environment
# ---------------------------------------------------------------------------

check_env() {
  if [ ! -f "$ENV_FILE" ]; then
    log_error ".env file not found."
    log_info "  cp .env.example .env && \$EDITOR .env"
    exit 1
  fi
}

# ---------------------------------------------------------------------------
# Service lifecycle
# ---------------------------------------------------------------------------

cmd_up() {
  show_banner
  check_env
  ensure_dynamic_ports
  log_step "Starting Mike platform (${#BOOT_ORDER[@]} services)..."
  $COMPOSE up -d "${@:---wait}"
  log_ok "All services started."
  cmd_health
}

cmd_down() {
  log_step "Stopping all services..."
  $COMPOSE down "$@"
  log_ok "All services stopped."
}

cmd_build() {
  check_env
  local service="${1:-}"
  if [ -n "$service" ]; then
    log_step "Building $service..."
    $COMPOSE build "$service"
  else
    log_step "Building all services..."
    $COMPOSE build
  fi
  log_ok "Build complete."
}

cmd_rebuild() {
  check_env
  local service="${1:-}"
  if [ -n "$service" ]; then
    log_step "Rebuilding $service (no cache)..."
    $COMPOSE build --no-cache "$service"
  else
    log_step "Rebuilding all services (no cache)..."
    $COMPOSE build --no-cache
  fi
  log_ok "Rebuild complete."
}

cmd_restart() {
  local service="${1:-}"
  if [ -n "$service" ]; then
    log_step "Restarting $service..."
    $COMPOSE restart "$service"
  else
    log_step "Restarting all services..."
    $COMPOSE restart
  fi
  log_ok "Restart complete."
}

cmd_logs() {
  local service="${1:-}"
  if [ -n "$service" ]; then
    $COMPOSE logs -f --tail=100 "$service"
  else
    $COMPOSE logs -f --tail=50
  fi
}

cmd_shell() {
  local service="${1:?Usage: ./ailegal.sh shell <service>}"
  log_step "Opening shell in $service..."
  $COMPOSE exec "$service" sh -c 'if command -v bash >/dev/null; then bash; else sh; fi'
}

# ---------------------------------------------------------------------------
# Health checks (three-layer: container → TCP → HTTP)
# ---------------------------------------------------------------------------

probe_service() {
  local service="$1"
  local probe="${HEALTH_PROBES[$service]:-}"
  if [ -z "$probe" ]; then
    echo "no probe"
    return 0
  fi

  # Layer 1: Container health
  local container_status
  container_status=$(docker inspect --format='{{.State.Health.Status}}' "${PROJECT_NAME}-${service}-1" 2>/dev/null || echo "missing")
  if [ "$container_status" = "missing" ]; then
    echo "not running"
    return 1
  fi

  # Layer 2: Docker health status
  if [ "$container_status" = "healthy" ]; then
    echo "healthy"
    return 0
  elif [ "$container_status" = "starting" ]; then
    echo "starting"
    return 1
  fi

  # Layer 3: HTTP/command probe
  if [[ "$probe" == cmd:* ]]; then
    local cmd="${probe#cmd:}"
    cmd=$(eval echo "$cmd")
    if $COMPOSE exec -T "$service" $cmd &>/dev/null; then
      echo "healthy"
      return 0
    fi
  elif [[ "$probe" == http* ]]; then
    local url
    url=$(eval echo "$probe")
    if curl -sf --max-time 5 "$url" &>/dev/null; then
      echo "healthy"
      return 0
    fi
  fi

  echo "unhealthy"
  return 1
}

cmd_health() {
  load_ports
  local total=0 healthy_count=0
  echo ""
  echo -e "${BOLD}Mike Platform — Health Status${NC}"
  echo ""
  printf "${CYAN}%-20s %-12s %-8s %-22s${NC}\n" "SERVICE" "STATUS" "PORT" "UPTIME"
  printf "%-20s %-12s %-8s %-22s\n" "───────────────────" "──────────" "──────" "─────────────────────"

  for service in "${BOOT_ORDER[@]}"; do
    total=$((total + 1))
    local status uptime_str port_str

    status=$(probe_service "$service")

    uptime_str=$(docker inspect --format='{{.State.StartedAt}}' "${PROJECT_NAME}-${service}-1" 2>/dev/null || echo "—")
    if [ "$uptime_str" != "—" ]; then
      uptime_str="${uptime_str:0:19}"
    fi

    # Find port for this service
    port_str="—"
    for i in "${!PORT_LABELS[@]}"; do
      local label="${PORT_LABELS[$i]}"
      if [[ "$label" == "$service" || "$label" == "${service//-/_}" ]]; then
        port_str="${!PORT_VARS[$i]}"
        break
      fi
    done

    local color="$RED"
    local icon="✗"
    case "$status" in
      healthy)  color="$GREEN"; icon="✓"; healthy_count=$((healthy_count + 1)) ;;
      starting) color="$YELLOW"; icon="◐" ;;
      *)        color="$RED"; icon="✗" ;;
    esac

    printf "${color} ${icon} %-18s %-12s${NC} %-8s ${DIM}%-22s${NC}\n" "$service" "$status" "$port_str" "$uptime_str"
  done

  echo ""
  if [ "$healthy_count" -eq "$total" ]; then
    echo -e "${GREEN}${BOLD}All $total services healthy.${NC}"
  else
    echo -e "${YELLOW}${BOLD}$healthy_count/$total services healthy.${NC}"
  fi
  echo ""
}

cmd_status() {
  cmd_health
  cmd_ports
}

# ---------------------------------------------------------------------------
# Smoke tests (curl-based probes)
# ---------------------------------------------------------------------------

cmd_smoke() {
  load_ports
  echo ""
  echo -e "${BOLD}Mike Platform — Smoke Tests${NC}"
  echo ""

  local pass=0 fail=0 skip=0

  smoke_probe() {
    local name="$1" url="$2" expect="${3:-200}"
    local code
    code=$(curl -sf -o /dev/null -w '%{http_code}' --max-time 10 "$url" 2>/dev/null || echo "000")
    if [[ "$code" =~ ^[23] ]]; then
      echo -e "  ${GREEN}✓${NC} $name → ${code}"
      pass=$((pass + 1))
    elif [ "$code" = "000" ]; then
      echo -e "  ${RED}✗${NC} $name → connection refused"
      fail=$((fail + 1))
    else
      echo -e "  ${RED}✗${NC} $name → ${code}"
      fail=$((fail + 1))
    fi
  }

  echo "  Probing services..."
  echo ""

  smoke_probe "nginx (proxy)"          "http://localhost:${NGINX_PORT:-80}/health"
  smoke_probe "frontend (Next.js)"     "http://localhost:${FRONTEND_PORT:-3000}/"
  smoke_probe "backend (Express)"      "http://localhost:${BACKEND_PORT:-3001}/health"
  smoke_probe "backend via proxy"      "http://localhost:${NGINX_PORT:-80}/api/health"
  smoke_probe "postgrest"              "http://localhost:${POSTGREST_PORT:-3002}/"
  smoke_probe "gotrue (auth)"          "http://localhost:${GOTRUE_PORT:-9999}/health"
  smoke_probe "minio (storage)"        "http://localhost:${MINIO_API_PORT:-9000}/minio/health/live"
  smoke_probe "minio console"          "http://localhost:${MINIO_CONSOLE_PORT:-9001}/"
  smoke_probe "pgadmin"                "http://localhost:${PGADMIN_PORT:-5050}/misc/ping"
  smoke_probe "glitchtip"              "http://localhost:${GLITCHTIP_PORT:-8000}/_health/"

  echo ""
  echo -e "${BOLD}Results: ${GREEN}$pass passed${NC}, ${RED}$fail failed${NC}"
  echo ""

  [ "$fail" -eq 0 ] && return 0 || return 1
}

# ---------------------------------------------------------------------------
# Database commands
# ---------------------------------------------------------------------------

cmd_db_migrate() {
  log_step "Running Prisma migrations..."
  $COMPOSE exec backend npx prisma migrate deploy
  log_ok "Migrations applied."
}

cmd_db_studio() {
  log_step "Opening Prisma Studio..."
  cd "$ROOT/backend" && npx prisma studio
}

cmd_db_seed() {
  log_step "Seeding database..."
  $COMPOSE exec backend npx prisma db seed
  log_ok "Database seeded."
}

cmd_db_backup() {
  check_env
  mkdir -p "$BACKUP_DIR"
  source "$ENV_FILE" 2>/dev/null || true
  local timestamp
  timestamp=$(date +%Y%m%d_%H%M%S)
  local filename="${BACKUP_DIR}/mike_${timestamp}.sql.gz"
  log_step "Backing up database to $filename..."
  $COMPOSE exec -T postgres pg_dump -U "${POSTGRES_USER:-mike}" "${POSTGRES_DB:-mike}" | gzip > "$filename"
  local size
  size=$(du -h "$filename" | cut -f1)
  log_ok "Backup saved: $filename ($size)"
}

cmd_db_restore() {
  local file="${1:?Usage: ./ailegal.sh db:restore <file.sql.gz>}"
  if [ ! -f "$file" ]; then
    log_error "File not found: $file"
    exit 1
  fi
  log_warn "This will overwrite the current database."
  read -r -p "Continue? [y/N] " confirm
  if [[ "$confirm" != [yY] ]]; then
    log_info "Cancelled."
    exit 0
  fi
  source "$ENV_FILE" 2>/dev/null || true
  log_step "Restoring from $file..."
  gunzip -c "$file" | $COMPOSE exec -T postgres psql -U "${POSTGRES_USER:-mike}" "${POSTGRES_DB:-mike}"
  log_ok "Database restored."
}

# ---------------------------------------------------------------------------
# Quality commands
# ---------------------------------------------------------------------------

cmd_test() {
  log_step "Running test suite..."
  local failed=0
  $COMPOSE exec backend npm test 2>/dev/null || { log_warn "Backend tests failed or not configured"; failed=1; }
  $COMPOSE exec frontend npm test 2>/dev/null || { log_warn "Frontend tests failed or not configured"; failed=1; }
  [ "$failed" -eq 0 ] && log_ok "All tests passed." || log_warn "Some tests failed."
  return "$failed"
}

cmd_lint() {
  log_step "Running linters..."
  $COMPOSE exec backend npm run lint 2>/dev/null || log_warn "Backend lint not configured"
  $COMPOSE exec frontend npm run lint
  log_ok "Lint complete."
}

# ---------------------------------------------------------------------------
# Version bumping
# ---------------------------------------------------------------------------

cmd_bump() {
  local type="${1:?Usage: ./ailegal.sh bump <patch|minor|major>}"
  case "$type" in
    patch|minor|major) ;;
    *) log_error "Invalid bump type: $type (use patch, minor, or major)"; exit 1 ;;
  esac

  cd "$ROOT/backend" && npm version "$type" --no-git-tag-version
  cd "$ROOT/frontend" && npm version "$type" --no-git-tag-version
  cd "$ROOT"

  local version
  version=$(node -p "require('./backend/package.json').version")
  git add backend/package.json frontend/package.json
  git commit -m "chore: bump version to v${version}"
  git tag "v${version}"
  log_ok "Bumped to v${version}"
}

# ---------------------------------------------------------------------------
# Reset commands
# ---------------------------------------------------------------------------

cmd_clean() {
  log_warn "Removing containers, volumes, and networks..."
  $COMPOSE down -v --remove-orphans
  [ -f "$PORTS_FILE" ] && rm -f "$PORTS_FILE"
  log_ok "Cleaned."
}

cmd_reset() {
  log_warn "This will DESTROY all data (volumes + database). This is irreversible."
  read -r -p "Type 'RESET' to confirm: " confirm
  if [ "$confirm" != "RESET" ]; then
    log_info "Cancelled."
    exit 0
  fi
  cmd_clean
  log_ok "Reset complete. Run './ailegal.sh up' to start fresh."
}

cmd_nuke() {
  log_warn "Full reset: clean + rebuild + migrate + seed"
  cmd_clean
  cmd_build
  cmd_up
  sleep 5
  cmd_db_migrate 2>/dev/null || log_warn "Migrations not ready yet"
  cmd_db_seed 2>/dev/null || log_warn "Seeding not ready yet"
  log_ok "Nuke complete. Fresh environment ready."
}

# ---------------------------------------------------------------------------
# Main router
# ---------------------------------------------------------------------------

show_banner() {
  echo -e "${CYAN}"
  cat << 'BANNER'
  ╔══════════════════════════════════════════════════════════════════╗
  ║                                                                ║
  ║    █████╗ ██╗    ██╗     ███████╗ ██████╗  █████╗ ██╗          ║
  ║   ██╔══██╗██║    ██║     ██╔════╝██╔════╝ ██╔══██╗██║          ║
  ║   ███████║██║    ██║     █████╗  ██║  ███╗███████║██║          ║
  ║   ██╔══██║██║    ██║     ██╔══╝  ██║   ██║██╔══██║██║          ║
  ║   ██║  ██║██║    ███████╗███████╗╚██████╔╝██║  ██║███████╗     ║
  ║   ╚═╝  ╚═╝╚═╝    ╚══════╝╚══════╝ ╚═════╝ ╚═╝  ╚═╝╚══════╝     ║
  ║                                                                ║
  ║          M I K E   P L A T F O R M   O R C H E S T R A T O R  ║
  ║          11 services · dynamic ports · self-hosted             ║
  ║                                                                ║
  ╚══════════════════════════════════════════════════════════════════╝
BANNER
  echo -e "${NC}"
}

cmd_help() {
  show_banner
  echo -e "${CYAN}LIFECYCLE${NC}"
  echo "  up                   Start all services (health-waited, dynamic ports)"
  echo "  down                 Stop all services"
  echo "  build [service]      Build containers"
  echo "  rebuild [service]    Force rebuild (no cache)"
  echo "  restart [service]    Restart service(s)"
  echo "  logs [service]       Tail logs (--tail=100)"
  echo "  shell <service>      Open shell in container"
  echo ""
  echo -e "${CYAN}MONITORING${NC}"
  echo "  health               Three-layer health check (container → TCP → HTTP)"
  echo "  status               Health + port allocation table"
  echo "  smoke                Curl-based smoke tests on all endpoints"
  echo "  ports                Port allocation map with conflict detection"
  echo "  ports:auto           Auto-reallocate conflicting ports"
  echo ""
  echo -e "${CYAN}DATABASE${NC}"
  echo "  db:migrate           Run Prisma migrations"
  echo "  db:studio            Open Prisma Studio"
  echo "  db:seed              Seed dev data"
  echo "  db:backup            Backup to timestamped .sql.gz"
  echo "  db:restore <file>    Restore from backup"
  echo ""
  echo -e "${CYAN}QUALITY${NC}"
  echo "  test                 Run Vitest test suite"
  echo "  lint                 Run linters"
  echo ""
  echo -e "${CYAN}VERSIONING${NC}"
  echo "  bump <type>          Version bump (patch/minor/major) + git tag"
  echo ""
  echo -e "${CYAN}RESET${NC}"
  echo "  clean                Remove containers, volumes, port overrides"
  echo "  reset                DESTRUCTIVE: clean + drop all data (requires confirmation)"
  echo "  nuke                 Full reset: clean + rebuild + migrate + seed"
  echo ""
}

case "${1:-help}" in
  up)           shift; cmd_up "$@" ;;
  down)         shift; cmd_down "$@" ;;
  build)        shift; cmd_build "$@" ;;
  rebuild)      shift; cmd_rebuild "$@" ;;
  restart)      shift; cmd_restart "$@" ;;
  logs)         shift; cmd_logs "$@" ;;
  shell)        shift; cmd_shell "$@" ;;
  health)       cmd_health ;;
  status)       cmd_status ;;
  smoke)        cmd_smoke ;;
  ports)        cmd_ports ;;
  ports:auto)   cmd_ports_auto ;;
  db:migrate)   cmd_db_migrate ;;
  db:studio)    cmd_db_studio ;;
  db:seed)      cmd_db_seed ;;
  db:backup)    cmd_db_backup ;;
  db:restore)   shift; cmd_db_restore "$@" ;;
  test)         cmd_test ;;
  lint)         cmd_lint ;;
  bump)         shift; cmd_bump "$@" ;;
  clean)        cmd_clean ;;
  reset)        cmd_reset ;;
  nuke)         cmd_nuke ;;
  help|*)       cmd_help ;;
esac
